stages:
  - test

image: denoland/deno:ubuntu-1.22.2

deno-lint:
  stage: test
  script:
    - deno lint --unstable

deno-test:
  stage: test
  script:
    - deno test --allow-net=data.jsdelivr.com,cdn.jsdelivr.net --unstable
